#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \setlength{\parskip}{0.3cm}
#+TITLE: 
#+OPTIONS:  toc:nil
#+LATEX_HEADER: \lhead{\includegraphics[width=1.5cm]{img/Logo-fiuba}} \chead{66.74  - Señales y Sistemas} \rhead{\Huge FIUBA}
#+LATEX_HEADER: \lfoot{88581 - Pandolfo Lucas} \cfoot{\thepage} \rfoot{$2^{do}$ cuatrimestre 2011}

* Principios básicos
** Ejercicio 1
   #+LABEL: fig-r-rangos
   #+CAPTION: \gamma-rangos
   #+ATTR_LaTeX: width=0.6\columnwidth placement=[H]
   [[file:img/r-rangos.pdf]]

#+BEGIN_LATEX
  \begin{eqnarray*}
    R_1 &=& sen(\eta_1) r_1 \\
    R_1 &=& sen(\eta_1) \left(r_0 + \frac{c\,T_s}{2}\right)\\
    \\
    R_0 &=& sen(\eta_0) r_0\\
    \\
    \Delta R_1 &=& R_1 - R_0 \\
    \Delta R_1 &=&  sen(\eta_1) \left(r_0 + \frac{c\,T_s}{2}\right) -  sen(\eta_0) r_0 \\
    \\
    \Delta R_k &=&  sen(\eta_k) \left(r_0 + \frac{k\,c\,T_s}{2}\right) -  sen(\eta_0) r_0 \\
    \\
    \gamma-rango_k = r_k &=& \frac{h}{cos(\eta_k)}\\
    \\
    \eta_k &=& cos^{-1}\left(\frac{h}{r_k}\right)
  \end{eqnarray*}  
#+END_LATEX

*** TODO graficos

\newpage

* Parte analógica
** Ejercicio 2

   La señal chirp se define como

   $$chirp(t) = e^{j\theta(t)}$$

   donde $\theta(t)$ es una función cuadrática del tiempo con forma

   $$\theta(t) = k_1 t^2 + k_2 t$$

   La frecuencia instantánea de la chirp es entonces:

   $$f\_inst(t) = 2 k_1 t + k_2$$

   Como la chirp barre frecuencias que van desde -20Mhz hasta 20Mhz en
   10$\mu s$:

   $$f\_inst(0) = 2 k_1 0 + k_2 = k2 = -20 Mhz$$

   Y al final

#+BEGIN_LATEX
  \begin{eqnarray*}
    f\_inst(10\mu s) = 2 k_1 10\mu s + k_2 &=& 20 Mhz \\
                       2 k_1 10\mu s - 20Mhz &=& 20 Mhz \\
                       k_1 &=& \frac{40Mhz}{2\, 10\mu s}\\
                       k_1 = 2\,\,10^{12}
  \end{eqnarray*}
#+END_LATEX

   Por lo tanto, la fase instantánea es

   $$f\_inst(t) =  4\,10^{12} t^2 - 20\,10^6 t$$

   En la figura \ref{fig-chirp-no-modulada} se puede ver el resultado
   de graficar las partes real e imaginarias de la chirp junto con la
   fase instantánea en función del tiempo.

    #+LABEL: fig-chirp-no-modulada
    #+CAPTION: Chirp emitida por el SARAT (no modulada)
    #+ATTR_LaTeX: angle=-90,width=0.9\columnwidth placement=[H]
#+begin_src octave :exports results :results file
  t = 0:1/Fs:10e-6
  chirp_nm = chirp_no_modulada(t);
  subplot(311);
  plot(t,real(chirp_nm), "linewidth", 3);
  title("Parte real");
  axis([0 t(end)])
  cambiarEjeX("%.00fus",1e6);
  subplot(312);
  plot(t,imag(chirp_nm), "linewidth", 3);
  title("Parte imaginaria");
  axis([0 t(end)])
  cambiarEjeX("%.00fus",1e6);
  subplot(313);
  plot(t,arg(chirp_nm), "linewidth", 3);
  title("Fase");
  axis([0 t(end) -pi pi])
  cambiarEjeX("%.00fus",1e6);
  set(gca, 'ytick', [-pi -pi/2 0 pi/2 pi])
  set(gca, 'interpreter', 'tex');
  set(gca,'YTickLabel',{'-\pi' '-\pi/2' '0' '\pi/2' '\pi'}, 'interpreter', 'tex');
  ans = guardarImagen("img/chirp-no-modulada.pdf");
#+end_src
#+results:
[[file:img/chirp-no-modulada.pdf]]

    #+LABEL: fig-chirp-no-modulada-no-nyquist
    #+CAPTION: Chirp emitida por el SARAT (no modulada) submuestreada
    #+ATTR_LaTeX: angle=-90,width=0.9\columnwidth placement=[H]
#+begin_src octave :exports results :results file
  t = 0:1/(Fs/2):10e-6
  chirp_nm = chirp_no_modulada(t);
  subplot(311);
  plot(t,real(chirp_nm), "linewidth", 3);
  title("Parte real");
  axis([0 t(end)])
  cambiarEjeX("%.00fus",1e6);
  subplot(312);
  plot(t,imag(chirp_nm), "linewidth", 3);
  title("Parte imaginaria");
  axis([0 t(end)])
  cambiarEjeX("%.00fus",1e6);
  subplot(313);
  plot(t,arg(chirp_nm), "linewidth", 3);
  title("Fase");
  axis([0 t(end) -pi pi])
  cambiarEjeX("%.00fus",1e6);
  set(gca, 'ytick', [-pi -pi/2 0 pi/2 pi])
  set(gca, 'interpreter', 'tex');
  set(gca,'YTickLabel',{'-\pi' '-\pi/2' '0' '\pi/2' '\pi'}, 'interpreter', 'tex');
  ans = guardarImagen("img/chirp-no-modulada-submuestreada.pdf");
#+end_src
#+results:
[[file:img/chirp-no-modulada-submuestreada.pdf]]

    #+LABEL: fig-espectro-chirp-no-modulada
    #+CAPTION: Espectro de la  Chirp emitida por el SARAT (no modulada)
    #+ATTR_LaTeX: width=0.9\columnwidth placement=[H]
#+begin_src octave :exports results :results file
  t = 0:1/(Fs):10e-6
  chirp_nm = chirp_no_modulada(t);
  espectro = fft(chirp_nm);
  plot(Fs/t(end) * t,20*log10(abs(espectro)), "linewidth", 3);
  axis([0 Fs 0 30])
  cambiarEjeX("%0.0fMhz", 1/1e6);
  cambiarEjeY("%ddB", 1);
  grid();
  ans = guardarImagen("img/espectro-chirp-no-modulada.pdf");
#+end_src
#+results:
[[file:img/espectro-chirp-no-modulada.pdf]]

   La chirp tiene una frecuencia máxima de 20Mhz y por Nyquist la
   mínima frecuencia de muestreo que podemos usar es 40Mhz, si no se
   satisface el criterio de Nyquist se producen resultados como el de
   la figura \ref{fig-chirp-no-modulada-no-nyquist}.


** Ejercicio 3

    #+LABEL: fig-chirp-no-modulada-espectrograma
    #+CAPTION: Espectrograma de la Chirp emitida por el SARAT (no modulada)
    #+ATTR_LaTeX: width=0.9\columnwidth placement=[H]
#+begin_src octave :exports results :results file
  t = 0:1/Fs:10e-6*10;
  chirp_nm = real(chirp_no_modulada(t))
  specgram(chirp_nm,[],Fs,50,49);
  ans = guardarImagen("img/chirp-no-modulada-espectro.pdf");
#+end_src
#+results:
[[file:img/chirp-no-modulada-espectro.pdf]]

    #+LABEL: fig-chirp-no-modulada-espectrograma-submuestreada
    #+CAPTION: Espectrograma de la Chirp emitida por el SARAT (no modulada) submuestreada
    #+ATTR_LaTeX: width=0.9\columnwidth placement=[H]
#+begin_src octave :exports results :results file
  t = 0:1/(Fs/2):10e-6*10;
  chirp_nm = real(chirp_no_modulada(t))
  specgram(chirp_nm,[],Fs/2,50,49);
  ans = guardarImagen("img/chirp-no-modulada-espectro-submuestreada.pdf");
#+end_src
#+results:
[[file:img/chirp-no-modulada-espectro-submuestreada.pdf]]

*** TODO Tipo y ancho de ventana, explicación

** Ejercicio 4

   La chirp está definida como:

   $$chirp(t) = e^{j \phi(t)}$$

   Donde $\phi(t)$ es la fase en función del tiempo.Como ya se mostró
   en el punto 2, la frecuencia instantánea
   $\left(\frac{\partial\phi}{\partial t}\right)$ de la chirp (figura
   \ref{fig-chirp-frecuencia-instantanea}) es

   $$f\_inst(t) = 2 k_1 t + k_2$$

   Donde $k_2$ es la frecuencia inicial y $2 k_1$ es el incremento de
   frecuencia por unidad de tiempo.

   #+LABEL: fig-chirp-frecuencia-instantanea
   #+CAPTION: Frecuencia instantánea de la chirp
   #+ATTR_LaTeX: width=0.9\columnwidth placement=[H]
#+begin_src octave :exports results :results file
  t = 0:1/Fs:10e-6;
  plot(t,4e12*t-20e6, 'linewidth', 5);
  axis([0 t(end)]);
  cambiarEjeX("%0.0fus", 1e6);
  cambiarEjeY("%0.0fMhz", 1/1e6);
  grid();
  ans = guardarImagen("img/chirp-frecuencia-instantanea.pdf");
#+end_src
#+results:
[[file:img/chirp-frecuencia-instantanea.pdf]]


*** TODO ancho de banda formalmente

** Ejercicio 5

   #+LABEL: fig-espectros-modulador-ideal
   #+CAPTION: Espectro de las señales en las diferentes fases del modulador (ideal)
   #+ATTR_LaTeX: width=0.9\columnwidth placement=[H]
#+begin_src octave :exports results :results file
  
  subplot(511);
  Fs=3000e6;
  t = 0:1/Fs:10e-6;
  chirp_nm = chirp_no_modulada(t);
  espectroA = fft(chirp_nm);
  plot(Fs/t(end) * t,20*log10(abs(espectroA)), "linewidth", 3);
  axis([0 Fs])
  cambiarEjeX("%0.0fMhz", 1/1e6);
  cambiarEjeY("%ddB", 1);
  grid();
  
  subplot(512);
  exponencial = e.^(j*2*pi*200e6*t);
  producto = chirp_nm .* exponencial;
  espectroCorrido = abs(fft(producto));
  plot(Fs/t(end) * t, 20*log10(espectroCorrido), "linewidth", 3);
  axis([0 Fs])
  cambiarEjeX("%0.0fMhz", 1/1e6);
  cambiarEjeY("%ddB", 1);
  grid();
  
  subplot(513);
  espectroReal = abs(fft(real(producto)));
  plot(Fs/t(end) * t, 20*log10(espectroReal), "linewidth", 3);
  axis([0 Fs])
  cambiarEjeX("%0.0fMhz", 1/1e6);
  cambiarEjeY("%ddB", 1);
  grid();
  
  subplot(514);
  coseno = cos(1100e6*2*pi*t);
  espectroCoseno = abs(fft( real(producto).*coseno ));
  plot(Fs/t(end) * t, 20*log10(espectroCoseno), "linewidth", 3);
  axis([0 Fs])
  cambiarEjeX("%0.0fMhz", 1/1e6);
  cambiarEjeY("%ddB", 1);
  grid();
  
  %filtro ideal
  subplot(515);
  filtro = zeros(1,length(t));
  fc1 = ceil((1300e6-30e6)*t(end));
  fc2 = ceil((1300e6+30e6)*t(end));
  filtro(1,fc1:fc2) = 1;
  
  fc1 = ceil((1700e6-30e6)*t(end));
  fc2 = ceil((1700e6+30e6)*t(end));
  filtro(1,fc1:fc2) = 1;
  
  espectroFiltro = espectroCoseno.*filtro;
  plot(Fs/t(end) * t, 20*log10(espectroFiltro), "linewidth", 3);
  axis([0 Fs])
  cambiarEjeX("%0.0fMhz", 1/1e6);
  cambiarEjeY("%ddB", 1);
  grid();
  
  ans = guardarImagen("img/espectros-modulador-ideal.pdf");
#+end_src
#+results:
   [[file:img/espectros-modulador-ideal.pdf]]

*** TODO atenuación (después de verificar que las cosas sean potables)

\newpage
* Parte digital
** Ejercicio 9
   #+LABEL: fig-datos-crudos
   #+CAPTION: Datos crudos del SARAT (subset)
   #+ATTR_LaTeX: width=0.9\columnwidth placement=[H]
#+begin_src octave :exports results :results file
  datos = cargarMatriz();
  colormap('gray');
  imagesc(20*log10(abs(datos)));
  ans = guardarImagen("img/datos-crudos.pdf");
#+end_src
#+results:
   [[file:img/datos-crudos.pdf]]

*** TODO cálculos

** Ejercicio 10

   #+LABEL: fig-chirp-real
   #+CAPTION: Chirp real del SARAT
   #+ATTR_LaTeX: width=0.9\columnwidth placement=[H]
#+begin_src octave :exports results :results file
  datos = cargarMatriz();
  subplot(311);
  plot(0:499,real(datos(1,16:515)),'linewidth', 4)
  title('Parte Real');
  subplot(312);
  plot(0:499,imag(datos(1,16:515)),'linewidth', 4)
  title('Parte Imaginaria');
  subplot(313);
  plot(0:499,angle(datos(1,16:515)),'linewidth', 4)
  title('Fase');
  axis([0 499 -pi pi])
  set(gca, 'ytick', [-pi -pi/2 0 pi/2 pi])
  set(gca, 'interpreter', 'tex');
  set(gca,'YTickLabel',{'-\pi' '-\pi/2' '0' '\pi/2' '\pi'}, 'interpreter', 'tex');
  ans = guardarImagen("img/chirp-real.pdf");
#+end_src
#+results:
   [[file:img/chirp-real.pdf]]

   #+LABEL: fig-chirp-real-espectro
   #+CAPTION: Chirp real del SARAT (espectro)
   #+ATTR_LaTeX: width=0.9\columnwidth placement=[H]
#+begin_src octave :exports results :results file
  datos = cargarMatriz();
  espectro = abs(fft(datos(1,17:516)));
  plot(20*log10(espectro), 'linewidth', 4)
  cambiarEjeX("%.0fMhz",1/10);
  grid();
  ans = guardarImagen("img/chirp-real-espectro.pdf");
#+end_src
#+results:
   [[file:img/chirp-real-espectro.pdf]]

** Ejercicio 11

   #+LABEL: fig-modulo-espectro-rango
   #+CAPTION: Modulo del espectro en rango
   #+ATTR_LaTeX: width=0.9\columnwidth placement=[H]
#+begin_src octave :exports results :results file
  datos = cargarMatriz();
  datos_no_chirp = datos(201:end,350:end);
  espectros = abs(fft(datos_no_chirp, [] ,2)); #fft de cada fila
  espectro = sum(espectros,2)/rows(datos_no_chirp);
  plot(20*log10(espectro), 'linewidth', 4)

  cambiarEjeY("%ddB", 1);

  grid();
  ans = guardarImagen("img/espectro-rango.pdf");
#+end_src
#+results:
   [[file:img/espectro-rango.pdf]]

   #+LABEL: fig-modulo-espectro-azimuth
   #+CAPTION: Modulo del espectro en azimuth
   #+ATTR_LaTeX: width=0.9\columnwidth placement=[H]
#+begin_src octave :exports results :results file
  datos = cargarMatriz();
  datos_no_chirp = datos(201:end,350:end);
  espectros = abs(fft(datos_no_chirp, [] ,1)); #fft de cada columna
  espectro = sum(espectros,1)/columns(datos_no_chirp);
  plot(20*log10(espectro), 'linewidth', 4)

  axis([0 length(espectro)]);

  cambiarEjeY("%ddB", 1);

  grid();
  ans = guardarImagen("img/espectro-azimuth.pdf");
#+end_src
#+results:
   [[file:img/espectro-azimuth.pdf]]

\newpage
* Compresión del pulso
** Ejercicio 13

   
   La correlación no es una operación conmutativa. La relación entre
   la correlación de dos funciones con su transformada de Fourier es
   la siguiente:
#+BEGIN_LATEX
  \begin{eqnarray*}
    {\mathcal F}| x[n] \star y[n]|(\Omega) &=& \sum_{n=-\infty}^{\infty} x[n] \star y[n] e^{-j\Omega n} \\
    &=& \sum_{n=-\infty}^{\infty} \sum_{k=-\infty}^{\infty} x[k] y^*[k-n] e^{-j\Omega n} \\
    &=& \sum_{k=-\infty}^{\infty} x[k] \sum_{n=-\infty}^{\infty} y^*[k-n] e^{-j\Omega n} \\
    &=& \sum_{k=-\infty}^{\infty} x[k] Y^*(\Omega) e^{j\Omega k} \\
    &=& \sum_{k=-\infty}^{\infty} x[k]  e^{j\Omega k}  Y^*(\Omega) \\
    &=& X(-\Omega)  Y^*(\Omega)
  \end{eqnarray*}
#+END_LATEX

*** TODO explicar la relación con la convolución. Contraejemplo de conmutatividad
\newpage   
* Compresión en rango
\newpage
* Compresión en azimuth
\newpage
* Algoritmo de compresión
